@NotificationService_HostAddress = http://localhost:5135

### Send notification
POST {{NotificationService_HostAddress}}/api/notifications
Content-Type: application/json
{
  "type": "Email",
  "to": "test@example.com",
  "subject": "Test",
  "message": "Hello world"
}